"""add grade

Revision ID: 26379deb3006
Revises: 615639be9f34
Create Date: 2022-10-20 23:05:44.830644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26379deb3006'
down_revision = '615639be9f34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'grade')
    # ### end Alembic commands ###
