"""initial

Revision ID: 615639be9f34
Revises: 
Create Date: 2022-10-20 23:02:28.220023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615639be9f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'age')
    # ### end Alembic commands ###
